language: python
python:
  - 3.0
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
 - pip install codecov
 - pip install pylint
script:
 - sh install_modules.sh
 - sh test.sh
after_success:
 - coverage combine
 - codecov
